Repository sig-code/remix-tutorial, pull requests merged in 2024-09, with the labels that each got.

#3 🩹 useEffectのimport漏れを修正
  app/root.tsx
Labels: bug

#4 📈 pr_agentを追加
  .github/workflows/pr_agent.yml
Labels: enhancement, Review effort [1-5]: 3

#5 shadcn/ui導入
  app/components/ui/button.tsx
  app/lib/utils.ts
  app/tailwind.css
  components.json
  package-lock.json
  package.json
  tailwind.config.ts
Labels: Review effort [1-5]: 4
